; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i8)

; TODO: Implement the rest of the tests once the signed fold code is working and the fold is actually noticeable in the tests.

define i1 @icmp_eq_urem_product(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_product(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

