; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i8)

define i1 @icmp_ugt_sremsmin_smin(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmin_smin(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[X]], -2147483648
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ugt i32 %r, -2147483648
  ret i1 %c
}

define i1 @icmp_ugt_sremsmin_sminp1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmin_sminp1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], -2147483647
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ugt i32 %r, -2147483647
  ret i1 %c
}

define i1 @icmp_ugt_sremsmin_smaxm1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmin_smaxm1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], 2147483646
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ugt i32 %r, 2147483646
  ret i1 %c
}

define i1 @icmp_ugt_sremsmin_smax(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmin_smax(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[X]], -2147483648
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ugt i32 %r, 2147483647
  ret i1 %c
}

define i1 @icmp_ult_sremsmin_smin(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmin_smin(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ult i32 %r, -2147483648
  ret i1 %c
}

define i1 @icmp_ult_sremsmin_sminp1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmin_sminp1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ult i32 %r, -2147483647
  ret i1 %c
}

define i1 @icmp_ult_sremsmin_sminp2(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmin_sminp2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], -2147483646
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ult i32 %r, -2147483646
  ret i1 %c
}

define i1 @icmp_ult_sremsmin_smax(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmin_smax(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], -2147483648
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], 2147483647
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, -2147483648
  %c = icmp ult i32 %r, 2147483647
  ret i1 %c
}

define i1 @icmp_ugt_srem5_smin(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_smin(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, -2147483648
  ret i1 %c
}

define i1 @icmp_ugt_srem5_m5(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_m5(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, -5
  ret i1 %c
}

define i1 @icmp_ugt_srem5_m4(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_m4(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], -4
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, -4
  ret i1 %c
}

define i1 @icmp_ugt_srem5_3(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_3(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], 3
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, 3
  ret i1 %c
}

define i1 @icmp_ugt_srem5_4(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_4(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, 4
  ret i1 %c
}

define i1 @icmp_ugt_srem5_smaxm1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_srem5_smaxm1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ugt i32 %r, 2147483646
  ret i1 %c
}

define i1 @icmp_ult_srem5_sminp1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_sminp1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, -2147483647
  ret i1 %c
}

define i1 @icmp_ult_srem5_m4(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_m4(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, -4
  ret i1 %c
}

define i1 @icmp_ult_srem5_m3(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_m3(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], -3
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, -3
  ret i1 %c
}

define i1 @icmp_ult_srem5_4(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_4(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], 4
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, 4
  ret i1 %c
}

define i1 @icmp_ult_srem5_5(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_5(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, 5
  ret i1 %c
}

define i1 @icmp_ult_srem5_smax(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_srem5_smax(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 5
  %c = icmp ult i32 %r, 2147483647
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_smin(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_smin(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, -2147483648
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_sminp1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_sminp1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, -2147483647
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_sminp2(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_sminp2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], -2147483646
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, -2147483646
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_smaxm2(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_smaxm2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[R]], 2147483645
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, 2147483645
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_smaxm1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_smaxm1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, 2147483646
  ret i1 %c
}

define i1 @icmp_ugt_sremsmax_smax(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ugt_sremsmax_smax(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp slt i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ugt i32 %r, 2147483647
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_smin(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_smin(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, -2147483648
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_sminp1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_sminp1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, -2147483647
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_sminp2(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_sminp2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, -2147483646
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_sminp3(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_sminp3(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], -2147483645
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, -2147483645
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_smaxm1(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_smaxm1(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[R]], 2147483646
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, 2147483646
  ret i1 %c
}

define i1 @icmp_ult_sremsmax_smax(i32 %x) {
; CHECK-LABEL: define i1 @icmp_ult_sremsmax_smax(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 2147483647
; CHECK-NEXT:    [[C:%.*]] = icmp sgt i32 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %r = srem i32 %x, 2147483647
  %c = icmp ult i32 %r, 2147483647
  ret i1 %c
}

; TODO: Add negative test for when icmp constant is not zero
; TODO: update_test_checks.py should be run on all test files to ensure that there is no diff caused in other tests because of this??
; TODO: Add negative multi-use test for when %r is used more than once

define i1 @icmp_eq_srem_product(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_commuted1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_commuted1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %z, %x
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_commuted2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_commuted2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %z, %y
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_commuted3(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_commuted3(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %z, %x
  %b = mul nsw i8 %z, %y
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_multi_use(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_multi_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[A]])
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[B]])
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i8 [[R]])
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  call void @use(i8 %a)
  %b = mul nsw i8 %y, %z
  call void @use(i8 %b)
  %r = srem i8 %a, %b
  call void @use(i8 %r)
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_ne_srem_product(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_ne_srem_product(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp ne i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp ne i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_no_flags1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_no_flags1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_no_flags2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_no_flags2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_product_not_common_op(i8 %x, i8 %y, i8 %u, i8 %v) {
; CHECK-LABEL: define i1 @icmp_eq_srem_product_not_common_op(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[U:%.*]], i8 [[V:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[U]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[V]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %u
  %b = mul nsw i8 %y, %v
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}
